services:
  gainstar-mysql:
    container_name: gainstar-mysql
    image: mariadb:10.1
    hostname: gainstar_mysql
    ports:
      - "8716:3306"
    environment:
      MYSQL_ROOT_PASSWORD: keepitsimplestupid
    volumes:
      - ./initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
